# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('travel_date_from', models.CharField(max_length=255)),
                ('travel_date_to', models.CharField(max_length=255)),
                ('trips', models.ManyToManyField(related_name='trips', to='first_app.Users')),
            ],
        ),
    ]
