# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180401_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travels', to='first_app.Users'),
        ),
    ]
